ALTER TABLE IF EXISTS public.draws
ADD COLUMN IF NOT EXISTS winning_numbers INTEGER[] DEFAULT ARRAY[]::INTEGER[];

ALTER TABLE IF EXISTS public.draws
ADD COLUMN IF NOT EXISTS jackpot_rollover NUMERIC DEFAULT 0;
